# Generated by Django 5.1.6 on 2025-03-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="trackers",
            field=models.ManyToManyField(
                blank=True, null=True, to="tracker.tracker", verbose_name="Задача"
            ),
        ),
    ]
