# Generated by Django 5.1.6 on 2025-03-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_trackers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="trackers",
        ),
    ]
