# Generated by Django 5.1.6 on 2025-03-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_trackers"),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracker",
            name="employee",
        ),
        migrations.AddField(
            model_name="tracker",
            name="employees",
            field=models.ManyToManyField(
                blank=True, null=True, to="employee.employee", verbose_name="Сотрудники"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="time",
            field=models.CharField(
                blank=True, null=True, verbose_name="Срок выполнения"
            ),
        ),
    ]
