# Generated by Django 5.1.6 on 2025-03-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_remove_employee_trackers"),
        ("tracker", "0002_remove_tracker_employee_tracker_employees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="trackers",
                to="employee.employee",
                verbose_name="Сотрудники",
            ),
        ),
    ]
